#include "Core.h"
#include "Utils.h"
#include "LED.h"


void LED_Init(void) {
    LED_PINSEL &= ~(LED_PIN_BIT(LED_1_BIT) | LED_PIN_BIT(LED_2_BIT) | LED_PIN_BIT(LED_3_BIT) | LED_PIN_BIT(LED_4_BIT));
    LED_PINMODE &= ~(LED_PIN_BIT(LED_1_BIT) | LED_PIN_BIT(LED_2_BIT) | LED_PIN_BIT(LED_3_BIT) | LED_PIN_BIT(LED_4_BIT));
    LED_PORT->FIODIR |= (BIT_TO_MASK(LED_1_BIT) | BIT_TO_MASK(LED_2_BIT) | BIT_TO_MASK(LED_3_BIT) | BIT_TO_MASK(LED_4_BIT));
    LED_PORT->FIOSET |= (BIT_TO_MASK(LED_1_BIT) | BIT_TO_MASK(LED_2_BIT) | BIT_TO_MASK(LED_3_BIT) | BIT_TO_MASK(LED_4_BIT));
}